server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/api/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/api/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/api/**


  config:
    import: optional:configserver:http://localhost:8085

#Okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-60785807.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa7y4kdtpOI7dpzg5d7
    client-secret: szifoOTLESsW2R2y-Y07Yu94iiUcFSAeLkErBKQe
    scopes: openid, profile, email, offline_access

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka