server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/microservices
    username: postgres
    password: hathaway

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
